spring.application.name=ai-mcp-server

spring.main.banner-mode=off
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

spring.ai.mcp.server.streamable-endpoint=/mcp
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.annotation-scanner.enabled=true
spring.ai.mcp.server.type=sync
spring.ai.mcp.server.name=weather-server
spring.ai.mcp.server.version=1.0.0

management.endpoints.web.exposure.include=mappings

